"""Create accounts table

Revision ID: 4ee8aeb416a8
Revises: c5ef18e0d271
Create Date: 2024-03-06 18:17:37.532632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee8aeb416a8'
down_revision = 'c5ef18e0d271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_type_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agency', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'agency', 'number', 'account_type_id', name='uq_bank_agency_number_account_type')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_agency'), ['agency'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_number'), ['number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_number'))
        batch_op.drop_index(batch_op.f('ix_accounts_agency'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
