"""Create account_types table

Revision ID: a9cde2838f45
Revises: 1d0a8f83de0b
Create Date: 2024-03-06 17:39:12.553157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cde2838f45'
down_revision = '1d0a8f83de0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_types_name'), ['name'], unique=True)

    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_constraint('banks_ispb_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_banks_ispb'), ['ispb'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banks_ispb'))
        batch_op.create_unique_constraint('banks_ispb_key', ['ispb'])

    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_types_name'))

    op.drop_table('account_types')
    # ### end Alembic commands ###
