"""Create currencies table

Revision ID: c5ef18e0d271
Revises: a9cde2838f45
Create Date: 2024-03-06 18:02:05.188482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ef18e0d271'
down_revision = 'a9cde2838f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_abbreviation'), ['abbreviation'], unique=True)
        batch_op.create_index(batch_op.f('ix_currencies_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_name'))
        batch_op.drop_index(batch_op.f('ix_currencies_abbreviation'))

    op.drop_table('currencies')
    # ### end Alembic commands ###
